<<<<<<< HEAD:MHC_Hospital_Redesign/Migrations/202107290431550_listingmodel.Designer.cs
﻿// <auto-generated />
namespace MHC_Hospital_Redesign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class listingmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listingmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202107290431550_listingmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
=======
// <auto-generated />
namespace MHC_Hospital_Redesign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class feedbacks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feedbacks));
        
        string IMigrationMetadata.Id
        {
            get { return "202107261541536_feedbacks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
>>>>>>> 8f516084943f71976be64189ebf22d1047f8cd49:MHC_Hospital_Redesign/Migrations/202107261541536_feedbacks.Designer.cs
