// <auto-generated />
namespace MHC_Hospital_Redesign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class feedbackCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feedbackCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202107261633235_feedback-Category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
