// <auto-generated />
namespace MHC_Hospital_Redesign.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class templtesandecards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(templtesandecards));
        
        string IMigrationMetadata.Id
        {
            get { return "202107260148054_templtesandecards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
